# Copyright 2025 Canonical Ltd.
# SPDX-FileCopyrightText: 2025-present Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: Release BESS Image

on:
  workflow_call:
    inputs:
      github_registry:
        description: "GitHub Container Registry URL"
        default: "ghcr.io"
        type: string

jobs:
  release-image:
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'omec-project'
    steps:
      - uses: actions/checkout@v6

      - name: Login to Aether Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.github_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Container Registry
        env:
          DOCKER_REGISTRY: ${{ inputs.github_registry }}/
          DOCKER_REPOSITORY: ${{ github.repository_owner }}/
        run: yes y | ./env/rebuild_images.py jammy64
