# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: Scorecard supply-chain security

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}
      publish_results:
        description: "Whether to publish results for badge generation"
        required: false
        type: boolean
        default: true
      retention_days:
        description: "Days to retain SARIF artifact"
        required: false
        type: number
        default: 5
      allowed_org:
        description: "Allowed repository owner organization"
        required: false
        type: string
        default: "omec-project"

permissions: read-all

jobs:
  score-analysis:
    runs-on: ubuntu-latest
    if: github.repository_owner == inputs.allowed_org
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see publish_results below).
      id-token: write
      contents: read
      actions: read
      # To allow GraphQL ListCommits to work
      issues: read
      pull-requests: read
      # To detect SAST tools
      checks: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch_name }}
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: ${{ inputs.publish_results }}

      - name: Upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: SARIF file
          path: results.sarif
          retention-days: ${{ inputs.retention_days }}

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
